language: go

branches:
    only:
        - travis-packages

git:
  depth: false

sudo: required

dist: bionic

services:
  - docker

go:
  - 1.13

before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md)|(\.png)|(\.pdf)|(\.html)|^(LICENSE)|^(docs)'
      then
        echo "Only doc files were updated, skip running the CI."
        travis_terminate 0
      fi

install: true

jobs:
  include:
    - stage: "Verify vendor, codegen, gofmt, golint, govet"
      name: "Verify vendor, codegen, gofmt, golint, govet"
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINARY=golangci-lint sh -s -- -d -b $(go env GOPATH)/bin v1.22.2
        - export GO111MODULE=on
      script:
        - make verify
        - make lint

    - stage: "Test on amd64"
      name: "build, smallbuild, crossbuild"
      arch: amd64
      before_script:
        - sudo apt-get install upx-ucl -y
        - sudo apt-get install gcc-aarch64-linux-gnu -y
        - sudo apt-get install libc6-dev-arm64-cross -y
        - sudo apt-get install gcc-arm-linux-gnueabi -y
        - sudo apt-get install libc6-dev-armel-cross -y
        - sudo apt-get install ruby ruby-dev rubygems build-essential
        - sudo gem install --no-documet fpm
        - export GOFLAGS=-mod=vendor
      script:
        - make
        - make bluetoothdevice
        - make smallbuild 
        - make crossbuild
        - make crossbuild GOARM=GOARM7
